version: '3'
services:
  node:
    build: 
      dockerfile: ./Dockerfile
      context: .
    container_name: deskManager_api
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 3001:3001
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: cktfCfcHGJdoupomcccNxCbohzEWeFEg
      MYSQL_HOST: viaduct.proxy.rlwy.net
      MYSQL_PORT: 33429
      MYSQL_DATABASE: railway

    depends_on:
      database:
        condition: service_healthy   

  database:
    image: mysql:8.0.29
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: deskManager
    healthcheck:
      # Deve aguardar o banco ficar operacional
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    ports:
      - "33061:3306"